// <auto-generated />
using System;
using Alaska_Calendar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alaska_Calendar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240831031945_SeedSeptmeberFlightPrices")]
    partial class SeedSeptmeberFlightPrices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alaska_Calendar.Models.FlightPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FlightPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 295m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 143m
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 87m
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 200m
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 289m
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 75m
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 172m
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 90m
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 234m
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 150m
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 291m
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 105m
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 77m
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 250m
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 142m
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 90m
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 180m
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 279m
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 75m
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 278m
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 239m
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2024, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 145m
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 88m
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2024, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 299m
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 143m
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 287m
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2024, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 83m
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 230m
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 166m
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 297m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
